###########
# 役職設定 #
###########

# 人数
peopleWerewolf: 2
peopleSeer: 1
peopleMedium: 1
peopleMadman: 1

# 能力使用回数
abilitiesSeer: 1
abilitiesMedium: 1

############
# その他設定 #
############

# アクションバーの表示/非表示
showActionbar: true

###########
# コマンド #
##########

# 開始コマンド
startupCommands:
  - gamerule sendCommandFeedback false # コマンドログ停止
  - gamerule commandBlockOutput false # コマンドログ停止
  - kill @e[type=item] # 落ちているアイテムの消去
  - gamerule naturalRegeneration false # 自然回復無効
  - gamerule doDaylightCycle false # 時間経過停止
  - gamerule doWeatherCycle false # 天候固定
  - gamerule fallDamage false # 落下ダメージ無効
  - gamerule showDeathMessages false # キルログ停止
  - gamerule keepInventory true # キープインベントリ

# 基本アイテム
basicItems:
  - minecraft:bow{Unbreakable:1,Enchantments:[{id:power,lvl:10000},{id:infinity,lvl:1}]}
  - minecraft:arrow

# 特殊アイテム
specialItems: